// Generated by CoffeeScript 2.2.0
var XRB;

function getTime(){
    return new Date(Date.now());
}

XRB = class XRB {
  constructor() {
    this.baseUrls = ['http://txscl.meshbits.io/', 'http://txscl000.meshbits.io/', 'https://kmd.explorer.supernet.org/'];
	this.baseUrl = "https://kmd.explorer.supernet.org/";		
	
	//this.socketUrl = "wss://kmd.explorer.supernet.org/socket.io/"			
    this.ws = null;    
    this.txApi = this.baseUrl + "api/tx/";
    this.blockApi = this.baseUrl + "api/block/";
    this.txFees = [0.000224, 0.0005];
    this.txFeeTimestamp = 0;
    this.txFeeInterval = 3000; // how often to query for a fee
    this.donationAddress = "LiVcWyeoPXNYekcdFkDr64QLG3u9G8BgLs";
  }    

  start(txCb, blockCb) {    
	
	var sockets = [null, null];		
	var baseLength = this.baseUrls.length;		
	for (var i = 0; i < baseLength; i++)	
	{	
		//console.log('i: ' + i + ', baseUrl: ' + this.baseUrls[i]);		
		if (i >= baseLength) 
			return;	
		var socket = io(this.baseUrls[i]); // ,{ forceNew: true }
		
		console.log(socket);
		socket.on('connect', function () {
			socket.emit('subscribe', 'inv');
		});
		socket.on('block', function (block) {
			console.log('onBlock event fired: ' + getTime() + ', ' + block + ', block data:');
			console.log(block);
			return blockCb({ count: block ? block.length : 0 });
		});
		socket.on('tx', function (payload) {
			console.log('onTx event fired: ' + getTime() + ', vout: ' + payload.valueOut);		
			return txCb({
				amount: !isNaN(parseFloat(payload.valueOut)) && isFinite(payload.valueOut) ? payload.valueOut : 0,
				fee: 0, // Math.random() * Math.abs(this.txFees[0] - this.txFees[1]) + Math.min.apply(0, this.txFees),
				link: this.baseURL + 'tx/' + payload.txid,
				donation: !!payload.vout.find((vout) => {
				  return Object.keys(vout)[0] === this.donationAddress;
				})
			});				
		});
		sockets[i] = socket;
	}
	//console.log(sockets);		
		
  }

  stop() {
	  
    for (var i = 0; i < this.baseUrls.length; i++)
		if (socket[i]) sockets[i].emit('end');		
  }

};

//# sourceMappingURL=xrb.js.map
